# Generated by Django 5.2 on 2025-05-07 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_foodlog_expiration_date_wastelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodlog',
            name='is_donated',
        ),
        migrations.RemoveField(
            model_name='wastelog',
            name='food_name',
        ),
        migrations.AddField(
            model_name='foodlog',
            name='status',
            field=models.CharField(default='Available', max_length=20),
        ),
        migrations.AddField(
            model_name='wastelog',
            name='food_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.foodlog'),
        ),
    ]
