# Generated by Django 5.2 on 2025-05-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_foodlog_is_donated_remove_wastelog_food_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrecord',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
